apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernel-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kernel-dev
  template:
    metadata:
      labels:
        app: kernel-dev
    spec:
      containers:
        - name: kernel-dev
          image: 192.168.178.43:5000/ubuntu_kernel_dev:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: kernel-dev-volume
              mountPath: /kernel_dev
      volumes:
        - name: kernel-dev-volume
          hostPath:
            path: /kernel_dev
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernel-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kernel-test
  template:
    metadata:
      labels:
        app: kernel-test
    spec:
      containers:
        - name: kernel-test
          image: 192.168.178.43:5000/ubuntu_kernel_test:latest
          ports:
            - containerPort: 8080
            - containerPort: 3389 
          volumeMounts:
            - name: kernel-dev-volume
              mountPath: /kernel_dev
      volumes:
        - name: kernel-dev-volume
          hostPath:
            path: /kernel_dev
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: kernel-dev-service
spec:
  type: LoadBalancer
  selector:
    app: kernel-dev
  ports:
    - port: 9090 
      targetPort: 8080 
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kernel-test-service
spec:
  type: LoadBalancer
  selector:
    app: kernel-test
  ports:
    - port: 9091 
      targetPort: 8080 
      protocol: TCP
    - port: 9080 
      targetPort: 3389 
      protocol: TCP

# For the access to the local registry on all nodes:
# 
# cat /etc/containerd/config.toml | grep config_path:
# 
# config_path = "/etc/containerd/certs.d"
# 
# cat /etc/containerd/certs.d/192.168.178.43:5000/hosts.toml:
# 
# server = "http://192.168.178.43:5000"
# 
# [host."http://192.168.178.43:5000"]
#   capabilities = ["pull", "resolve", "push"]
#
# Deployment: kubectl apply -f Kubernetes_vanilla.yaml
#
# Check default namespace: kubectl get pods -o wide && kubectl get deployments && kubectl get services
#
# Pod check on the worker node: crictl pods
#
# kubectl proxy --address='0.0.0.0' --accept-hosts='^.*$' and http://<IP ADDRESS>:8001/api/v1/namespaces/default/services/kernel-dev-service:9090/proxy/
