apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernel-test
spec:
  replicas: {{ .Values.kernelTest.replicaCount }}
  selector:
    matchLabels:
      app: kernel-test
  template:
    metadata:
      labels:
        app: kernel-test
    spec:
      nodeName: {{ .Values.kernelTest.nodeName }}
      containers:
        - name: kernel-test
          image: {{ .Values.kernelTest.image }}
          env:
            - name: ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: root-password
                  key: password
          command: ["sh", "-c", "echo root:$ROOT_PASSWORD | chpasswd && service xrdp start && service ssh start && while true; do BODY=\"The Kubernetes pod for testing the A-EON PowerPC Linux kernels works!\n\n$(uname -a)\n\n$(free -m)\n\n$(lscpu | grep Model)\n\n$(LC_ALL=C mpstat -P ALL 1 1 | awk '$0 !~ /Average/ && $0 ~ /[0-9]+/ && $NF ~ /^[0-9.]+$/ { cpu=$(NF-10); if (cpu ~ /^[0-9]+$/) printf \"CPU%s: %.1f%%\\n\", cpu, 100-$NF }')\"; { printf \"HTTP/1.1 200 OK\\r\\nContent-Type: text/plain\\r\\nContent-Length: %s\\r\\nConnection: close\\r\\n\\r\\n%s\" \"${#BODY}\" \"$BODY\"; } | nc -l -p 8080; done"]
          ports:
            - containerPort: 8080
            - containerPort: 3389
          volumeMounts:
            - name: kernels
              mountPath: /kernels
      volumes:
        - name: kernels
          persistentVolumeClaim:
            claimName: nfs-pvc
