apiVersion: v1
kind: Service
metadata:
  name: kernel-dev-service
spec:
  type: ClusterIP
  selector:
    app: kernel-dev
  ports:
    - port: {{ .Values.kernelDev.servicePort }}
      targetPort: {{ .Values.kernelDev.containerPort }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kernel-test-service
spec:
  type: NodePort
  selector:
    app: kernel-test
  ports:
    - name: http
      port: {{ (index .Values.kernelTest.servicePorts 0).http }}
      targetPort: {{ (index .Values.kernelTest.containerPorts 0).http }}
      nodePort: {{ (index .Values.kernelTest.servicePorts 0).nodePort }}
      protocol: TCP
    - name: rdp
      port: {{ (index .Values.kernelTest.servicePorts 1).rdp }}
      targetPort: {{ (index .Values.kernelTest.containerPorts 1).rdp }}
      nodePort: {{ (index .Values.kernelTest.servicePorts 1).nodePort }}
      protocol: TCP
